### ISSUE TITLE
Does not work with python3.10

### ISSUE THREAD

**Issue by kate-holdener** [dmc314/pickflip#6]
When running this code on python 3.10, I get an error from pylogit module. Looks like pylogit is not yet compatible with python 3.10. Python 3.10 removed Iterable from collections

from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by dmc314** [comment]
ah bummer. i am running python 3.8.10.
Currently, pylogit is pivotal to the way results are calculated, but perhaps we can see if there is a different method or algorithm that can be used for this.

**Comment by kate-holdener** [comment]
We can run with python 3.8 for now. Maybe pylogit will update soon. I just wanted to note this, so that others would know.
